protected/models/Agenda.php
<?php

/**
 * This is the model class for table "agendamiento.agenda".
 *
 * The followings are the available columns in table 'agendamiento.agenda':
 * @property integer $idagenda
 * @property integer $idtipoagenda
 * @property integer $idpaciente
 * @property integer $idmedico
 * @property integer $idsubcentro
 * @property string $nombre
 * @property integer $numeroturno
 * @property string $fecha
 * @property string $horainicio
 * @property string $horafin
 * @property boolean $estado
 * @property string $creadopor
 * @property string $modificadopor
 * @property string $fechacreado
 * @property string $fechamodificado
 * @property boolean $atendido
 *
 * The followings are the available model relations:
 * @property Medico $idmedico
 * @property Paciente $idpaciente
 * @property Subcentro $idsubcentro
 * @property Tipoagenda $idtipoagenda
 */
class Agenda extends CActiveRecord
{
    public $sql;
    public $arrayDataProvider;
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'agendamiento.agenda';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
	return array(
        array('idtipoagenda, idpaciente, idmedico, fecha, nombre, numeroturno, horainicio, horafin', 'required'),
        array('idtipoagenda, idpaciente, idsubcentro, numeroturno, telefono,celular', 'numerical', 'integerOnly'=>true),
        array('nombre, creadopor,fecha, modificadopor,fechacreado', 'length', 'max'=>50),
        array('atendido', 'boolean'),
        array('estado, fechacreado,fechamodificado,telefono,celular', 'safe'),
        // The following rule is used by search().
	// @todo Please remove those attributes that should not be searched.
        array('idagenda, idtipoagenda, idpaciente, idmedico, idsubcentro, nombre, numeroturno, fecha, horainicio, horafin, estado, creadopor, modificadopor, fechacreado,apellido, fechamodificado, nombredoc, telefono, celular,nombresub,nombretipoag,nombrepac,historial,atendido, titulo, fx,canton,cedu', 'safe', 'on'=>'search'),
        array('idagenda, idtipoagenda, idpaciente, idmedico, idsubcentro, nombre, numeroturno, fecha, horainicio, horafin, estado, creadopor, modificadopor, fechacreado, fechamodificado, agenda, paciente, doctor, f1, f2', 'safe', 'on'=>'busqueda1'),
        array('idagenda, idtipoagenda, idpaciente, idmedico, idsubcentro, nombre, numeroturno, fecha, horainicio, horafin, estado, creadopor, modificadopor, fechacreado, fechamodificado, agenda1,f3, f4', 'safe', 'on'=>'busqueda2'),
        array('idagenda, idtipoagenda, idpaciente, idmedico, idsubcentro, nombre, numeroturno, fecha, horainicio, horafin, estado, creadopor, modificadopor, fechacreado, fechamodificado, f3, f4, centro', 'safe', 'on'=>'busqueda3'),
        array('atendido', 'safe'),
        array('idagenda, idtipoagenda, idpaciente, idmedico, idsubcentro, nombre, numeroturno, fecha, horainicio, horafin, estado, creadopor, modificadopor, fechacreado, fechamodificado, agenda1,f3, f4', 'safe', 'on'=>'busqueda4'),
        array('idagenda, idtipoagenda, idpaciente, idmedico, idsubcentro, nombre, numeroturno, fecha, horainicio, horafin, estado, creadopor, modificadopor, fechacreado, fechamodificado, fs,centro, atendido, nuevafecha, idespecialidad', 'safe', 'on'=>'busqueda5'),
        array('idagenda, idtipoagenda, idpaciente, idmedico, idsubcentro, nombre, numeroturno, fecha, horainicio, horafin, estado, creadopor, modificadopor, fechacreado, fechamodificado, fs,centro, atendido, nuevafecha, especialidad, cantidad', 'safe', 'on'=>'busquedaEspecialidad'),
        array('especialidad, cantidad', 'safe'), 
        );
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'pkmedico' => array(self::BELONGS_TO, 'Medico', 'idmedico'),
			'pkpaciente' => array(self::BELONGS_TO, 'Paciente', 'idpaciente'),
			'pksubcentro' => array(self::BELONGS_TO, 'Subcentro', 'idsubcentro'),
			'pktipoagenda' => array(self::BELONGS_TO, 'Tipoagenda', 'idtipoagenda'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'idagenda' => 'Idagenda',
			'idtipoagenda' => 'Tipo de Agenda',
			'idpaciente' => 'Paciente',
			'idmedico' => 'Profesional de la Salud',
			'idsubcentro' => 'Centro de Salud',
			'nombre' => 'Nombre Del Paciente',
			'numeroturno' => 'Numero de Turno',
			'fecha' => 'Fecha de atención',
                        'telefono' => 'Teléfono',
			'celular' => 'Celular',
			'horainicio' => 'Hora Atención',
			'horafin' => 'Hora Fin',
			'estado' => 'Estado',
			'creadopor' => 'Creadopor',
			'modificadopor' => 'Modificadopor',
			'fechacreado' => 'Fecha Agendada',
			'fechamodificado' => 'Fechamodificado',
                        'atendido'=> 'Atendido',
                        
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
        public $nombredoc;
        public $nombresub;
        public $nombrepac;
        public $nombretipoag;
        public $apellido;
        public $historial;
        public $fx;
        public $cedu;
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('idagenda',$this->idagenda);
		$criteria->compare('t.idtipoagenda',$this->idtipoagenda);
		$criteria->compare('idpaciente',$this->idpaciente);
		$criteria->compare('idmedico',$this->idmedico);
		$criteria->compare('idsubcentro',$this->idsubcentro);
		$criteria->compare('LOWER(t.nombre)',$this->nombre,true);
		$criteria->compare('numeroturno',$this->numeroturno);
		$criteria->compare('t.fecha',$this->fecha);
                if((isset($this->fx) && trim($this->fx) != "")) { 
                  $criteria->compare('t.fecha',$this->fx);  
                } 
                $criteria->compare('telefono',$this->telefono);
		$criteria->compare('celular',$this->celular);
		$criteria->compare('horainicio',$this->horainicio,true);
		$criteria->compare('horafin',$this->horafin,true);
		$criteria->compare('t.estado',$this->estado);
		$criteria->compare('t.creadopor',$this->creadopor,true);
		$criteria->compare('modificadopor',$this->modificadopor,true);
		$criteria->compare('t.fechacreado',$this->fechacreado);
		$criteria->compare('fechamodificado',$this->fechamodificado,true);    
                $criteria->with = array('pkmedico','pksubcentro','pkpaciente','pktipoagenda');
                
                $criteria->addSearchCondition("UPPER(pkmedico.nombre ||' '||pkmedico.apellido)",strtoupper($this->nombredoc), true);
                $criteria->addSearchCondition("UPPER(pkpaciente.historialclinico)",strtoupper($this->historial), true);
                $criteria->addSearchCondition("UPPER(pkpaciente.cedula)",strtoupper($this->cedu), true);
                $criteria->addSearchCondition('UPPER(pkmedico.idespecialidad1->especialidad)',strtoupper($this->especialidad), true);
  
                $criteria->addSearchCondition('UPPER(pksubcentro.subcentro)',strtoupper($this->nombresub), true);
                $criteria->addSearchCondition("UPPER(pkpaciente.nombre ||' '|| pkpaciente.apellido)",strtoupper($this->nombrepac));
                $criteria->addSearchCondition('UPPER(pktipoagenda.tipoagenda)',strtoupper($this->nombretipoag), true);
                $criteria->order = 'idagenda DESC';
		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
       
        public function searchmedico($v)
	{
		// @todo Please modify the following code to remove attributes that should not be searched.
                $date = date_format(date_create(), 'Y-m-d');
		$criteria=new CDbCriteria;

		$criteria->compare('idagenda',$this->idagenda);
		$criteria->compare('idtipoagenda',$this->idtipoagenda);
		$criteria->compare('idpaciente',$this->idpaciente);
		$criteria->compare('t.idmedico',$v);
		$criteria->compare('idsubcentro',$this->idsubcentro);
		$criteria->compare('LOWER(t.nombre)',$this->nombre,true);
		$criteria->compare('numeroturno',$this->numeroturno);
		$criteria->compare('fecha',$date);
                $criteria->compare('telefono',$this->telefono);
		$criteria->compare('celular',$this->celular);
		$criteria->compare('horainicio',$this->horainicio,true);
		$criteria->compare('horafin',$this->horafin,true);
		$criteria->compare('t.estado',$this->estado);
		$criteria->compare('creadopor',$this->creadopor,true);
		$criteria->compare('modificadopor',$this->modificadopor,true);
		$criteria->compare('fechacreado',$this->fechacreado,true);
		$criteria->compare('fechamodificado',$this->fechamodificado,true);
                $criteria->compare('atendido',$this->atendido,true);
                $criteria->with = array('pkmedico','pksubcentro','pkpaciente','pktipoagenda');
                
                $criteria->addSearchCondition("LOWER(pkmedico.nombre ||' '||pkmedico.apellido)",$this->nombredoc, true);
  
                $criteria->addSearchCondition('LOWER(pksubcentro.subcentro)',$this->nombresub, true);
                $criteria->addSearchCondition('LOWER(pkpaciente.nombre)',$this->nombrepac, true);
                $criteria->addSearchCondition('LOWER(pktipoagenda.tipoagenda)',$this->nombretipoag, true);

protected/models/Medico.php
<?php

/**
 * This is the model class for table "agendamiento.medico".
 *
 * The followings are the available columns in table 'agendamiento.medico':
 * @property integer $idmedico
 * @property integer $idespecialidad
 * @property string $nombre
 * @property string $apellido
 * @property string $cedula
 * @property string $telefono
 * @property boolean $estado
 * @property string $creadopor
 * @property string $modificadopor
 * @property string $fechacreado
 * @property string $fechamodificado
 * @property integer $idusuario
 * @property integer $intervalo
 *
 * The followings are the available model relations:
 * @property Evento[] $eventos
 * @property Especialidadmedica $idespecialidad
 * @property Usuario $idusuario
 * @property Dia[] $dias
 * @property Agenda[] $agendas
 * @property Porcentajes[] $porcentajes
 * @property Agendaextra[] $agendaextras
 */
class Medico extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'agendamiento.medico';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('idespecialidad, nombre, apellido, cedula, intervalo', 'required'),
			array('idespecialidad, idusuario, intervalo', 'numerical', 'integerOnly'=>true),
			array('nombre, apellido', 'length', 'max'=>35),
			array('cedula, telefono', 'length', 'max'=>10),
                        array ('intervalo','length', 'max'=>2),
                        array('cedula','unique', 'message' => 'Esta cedula ya existe'),
			array('creadopor, modificadopor', 'length', 'max'=>50),
			array('estado, telefono,fechacreado, fechamodificado,titulo', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('idmedico, idespecialidad, nombre, apellido, cedula, telefono, estado, creadopor, modificadopor, fechacreado, fechamodificado, idusuario, especialidad,intervalo,nombreusu', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'eventos' => array(self::HAS_MANY, 'Evento', 'idmedico'),
			'idespecialidad1' => array(self::BELONGS_TO, 'Especialidadmedica', 'idespecialidad'),
			'pkusuario' => array(self::BELONGS_TO, 'Usuario', 'idusuario'),
                        'pkidusuario' => array(self::BELONGS_TO, 'Usuario', 'idusuario'),
			'dias' => array(self::HAS_MANY, 'Dia', 'idmedico'),
			'agendas' => array(self::HAS_MANY, 'Agenda', 'idmedico'),
			'porcentajes' => array(self::HAS_MANY, 'Porcentajes', 'idenmedico'),
			'agendaextras' => array(self::HAS_MANY, 'Agendaextra', 'idmedico'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'idmedico' => 'Profesional de la Salud',
			'idespecialidad' => 'Especialidad',
			'nombre' => 'Nombre',
			'apellido' => 'Apellido',
			'cedula' => 'Cedula',
			'telefono' => 'Telefono',
			'estado' => 'Estado',
			'creadopor' => 'Creadopor',
			'modificadopor' => 'Modificadopor',
			'fechacreado' => 'Fechacreado',
			'fechamodificado' => 'Fechamodificado',
			'idusuario' => 'Idusuario',
			'intervalo' => 'Intervalo',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditidusuarioions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
        public $especialidad;
        public $nombreusu;
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.
		$criteria=new CDbCriteria;
		
		$criteria->compare('idmedico',$this->idmedico);
		$criteria->compare('idespecialidad',$this->idespecialidad);
		$criteria->with = array ('idespecialidad1','pkidusuario');
                $criteria->addSearchCondition('UPPER(idespecialidad1.especialidad)', strtoupper($this->especialidad), true);		
		$criteria->compare('UPPER(t.nombre)',strtoupper($this->nombre),true);
		$criteria->compare('UPPER(t.apellido)',strtoupper($this->apellido),true);
		$criteria->compare('cedula',$this->cedula,true);
		$criteria->compare('telefono',$this->telefono,true);
		//$criteria->compare('t.estado',true);
		$criteria->compare('t.creadopor',$this->creadopor,true);
		$criteria->compare('t.modificadopor',$this->modificadopor,true);
		$criteria->compare('fechacreado',$this->fechacreado,true);
		$criteria->compare('fechamodificado',$this->fechamodificado,true);
		$criteria->compare('idusuario',$this->idusuario);
                $criteria->compare('intervalo',$this->intervalo);
                $criteria->compare('pkidusuario.nombre',$this->nombreusu);
                $criteria->order = 't.apellido ASC';
		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Medico the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

        public function getNombreCompleto()
    {
        return $this->nombre.' '.$this->apellido;
    }
       public function getFullname()
    {
        return $this->apellido.' '.$this->nombre;
    }
    public function getFullnameEspe()
    {
        return $this->idespecialidad1->especialidad.' ( '.$this->apellido.' '.$this->nombre.' )';
    }
    

        
   
}

protected/views/agenda/ExcelAgenda.php
<?php $contador=count($model); if ($model !== null):?>

<html>
<head>
<style>
 body {font-family: sans-serif;
 font-size: 10pt;
 }
 p { margin: 0pt;
 }
 td { vertical-align: top; }
 .items td {
 border-left: 0.1mm solid #000000;
 border-right: 0.1mm solid #000000;
 }
 table thead td { background-color: #EEEEEE;
 text-align: center;
 border: 0.1mm solid #000000;
 }
 .items td.blanktotal {
 background-color: #FFFFFF;
 border: 0mm none #000000;
 border-top: 0.1mm solid #000000;
 }
 .items td.totals {
 text-align: right;
 border: 0.1mm solid #000000;
 }
</style>
</head>
<body>
 <center>   <h3>Hospital General Rodriguez Zambrano De Manta</h3> </center> 
 <center>  <h4> Pacientes agendados por tipo de agenda</h4> </center>

<div style="text-align: right"><b>Fecha: </b><?php echo date("d/m/Y"); ?> </div>
<div style="text-align: right"><b>Total: </b> <?php echo $contador; ?></div>

<br>
 <table class="items" width="100%" style="font-size: 9pt; border-collapse: collapse;" cellpadding="5">
 <thead>
 <tr>
 <td width="16.666666666667%">Fecha</td>
 <td width="16.666666666667%">Profesional de la salud</td>
 <td width="16.666666666667%">Nombre del paciente</td>
 <td width="16.666666666667%">Tipo de agenda</td>
 <td width="16.666666666667%">Número de turno</td>
 <td width="16.666666666667%">Hora de inicio</td>
 <td width="16.666666666667%">Hora fin</td>

 </tr>
 </thead>
 <tbody>
 <!-- ITEMS -->
 <?php foreach($model as $row): ?>
 <tr>
 <td align="center">
 <?php echo $row->fecha; ?>
 </td>
 <td align="center">
 <?php echo $row->pkmedico->nombreCompleto;?>
 </td>
 <td align="center">
 <?php echo $row->pkpaciente->nombreCompleto;?>
 </td>
 <td align="center">
 <?php echo $row->pktipoagenda->tipoagenda;?>
 </td> 
 <td align="center">
 <?php echo $row->numeroturno;?>
 </td>
 <td align="center">
 <?php echo $row->horainicio;?>
 </td> 
  <td align="center">
 <?php echo $row->horafin;?>
 </td> 
 </tr>
 <?php endforeach; ?>
 <!-- FIN ITEMS -->
 <tr>
 <td class="blanktotal" colspan="6" rowspan="6"></td>
 </tr>
 </tbody>
 </table>
 </body>
 </html>
<?php endif; ?>

protected/views/agenda/ExcelDoctor.php
<?php $contador=count($model); if ($model !== null):?>

<html>
<head>
<style>
 body {font-family: sans-serif;
 font-size: 10pt;
 }
 p { margin: 0pt;
 }
 td { vertical-align: top; }
 .items td {
 border-left: 0.1mm solid #000000;
 border-right: 0.1mm solid #000000;
 }
 table thead td { background-color: #EEEEEE;
 text-align: center;
 border: 0.1mm solid #000000;
 }
 .items td.blanktotal {
 background-color: #FFFFFF;
 border: 0mm none #000000;
 border-top: 0.1mm solid #000000;
 }
 .items td.totals {
 text-align: right;
 border: 0.1mm solid #000000;
 }
</style>
</head>
<body>
<center>   <h3>Hospital General Rodriguez Zambrano De Manta</h3> </center> 
  <center>  <h4> Pacientes agendados por profesional de la salud</h4> </center> 

<div style="text-align: right"><b>Fecha: </b><?php echo date("d/m/Y"); ?> </div>
<div style="text-align: right"><b>Total: </b> <?php echo $contador; ?></div>

<br>
 <table class="items" width="100%" style="font-size: 9pt; border-collapse: collapse;" cellpadding="5">
 <thead>
 <tr>
 <td width="16.666666666667%">Fecha</td>
 <td width="16.666666666667%">Profesional de la salud</td>
 <td width="16.666666666667%">Nombre del paciente</td>
 <td width="16.666666666667%">Tipo de agenda</td>
 <td width="16.666666666667%">Numero de turno</td>
 <td width="16.666666666667%">Hora de incio</td>
 <td width="16.666666666667%">Hora de fin</td>
 </tr>
 </thead>
 <tbody>
 <!-- ITEMS -->
 <?php foreach($model as $row): ?>
 <tr>
 <td align="center">
 <?php echo $row->fecha; ?>
 </td>
 <td align="center">
 <?php echo $row->pkmedico->nombreCompleto;?>
 </td>
 <td align="center">
 <?php echo $row->pkpaciente->nombreCompleto;?>
 </td>
 <td align="center">
 <?php echo $row->pktipoagenda->tipoagenda;?>
 </td> 
 <td align="center">
 <?php echo $row->numeroturno;?>
 </td>
 <td align="center">
 <?php echo $row->horainicio;?>
 </td> 
  <td align="center">
 <?php echo $row->horafin;?>
 </td> 
 </tr>
 <?php endforeach; ?>
 <!-- FIN ITEMS -->
 <tr>
 <td class="blanktotal" colspan="6" rowspan="6"></td>
 </tr>
 </tbody>
 </table>
 </body>
 </html>
<?php endif; ?>

protected/views/agenda/ReportDoctorPaci15Dias.php
<?php $contador=count($model); if ($model !== null):?>

<html>
<head>
<style>
 body {font-family: sans-serif;
 font-size: 10pt;
 }
 p { margin: 0pt;
 }
 td { vertical-align: top; }
 .items td {
 border-left: 0.1mm solid #000000;
 border-right: 0.1mm solid #000000;
 }
 table thead td { background-color: #EEEEEE;
 text-align: center;
 border: 0.1mm solid #000000;
 }
 .items td.blanktotal {
 background-color: #FFFFFF;
 border: 0mm none #000000;
 border-top: 0.1mm solid #000000;
 }
 .items td.totals {
 text-align: right;
 border: 0.1mm solid #000000;
 }
</style>
</head>
<body>
 
<!--mpdf
 <htmlpageheader name="myheader">
 <table width="100%"><tr>
 <td width="50%" style="color:#0000BB;"><span style="font-weight: bold; font-size: 14pt;">Hospital General Rodriguez Zambrano De Manta</span><br />Manta-Ecuador<br /><span style="font-size: 15pt;">&#9742;</span> falta</td>
 <td width="50%" style="text-align: right;"><b>Pacientes atendidos en los ultimos 15 días por profesional de la salud</b></td>
 </tr></table>
 </htmlpageheader>
 
<htmlpagefooter name="myfooter">
 <div style="border-top: 1px solid #000000; font-size: 9pt; text-align: center; padding-top: 3mm; ">
 Página {PAGENO} de {nb}
 </div>
 </htmlpagefooter>
 
<sethtmlpageheader name="myheader" value="on" show-this-page="1" />
 <sethtmlpagefooter name="myfooter" value="on" />
 mpdf-->
<div style="text-align: right"><b>Fecha: </b><?php echo date("d/m/Y"); ?> </div>
<div style="text-align: right"><b>Total: </b> <?php echo $contador; ?></div>

<br>
 <table class="items" width="100%" style="font-size: 9pt; border-collapse: collapse;" cellpadding="5">
 <thead>
 <tr>
 <td width="16.666666666667%">Fecha</td>
 <td width="16.666666666667%">Profesional de la salud</td>
 <td width="16.666666666667%">Nombre del paciente</td>
 <td width="16.666666666667%">Tipo de agenda</td>
 <td width="16.666666666667%">Numero de turno</td>
 <td width="16.666666666667%">Estado</td>
 </tr>
 </thead>
 <tbody>
 <!-- ITEMS -->
 <?php foreach($model as $row): ?>
 <tr>
 <td align="center">
 <?php echo $row->fecha; ?>
 </td>
 <td align="center">
 <?php echo $row->pkmedico->nombreCompleto;?>
 </td>
 <td align="center">
 <?php echo $row->pkpaciente->nombreCompleto;?>
 </td>
 <td align="center">
 <?php echo $row->pktipoagenda->tipoagenda;?>
 </td> 
 <td align="center">
 <?php echo $row->numeroturno;?>
 </td>
 <td align="center">
 <?php 
 if($row->atendido == 1){
     echo "Atendido";
 } else{
     echo "No atendido";
 }
 ?>
 </td>
 </tr>
 <?php endforeach; ?>
 <!-- FIN ITEMS -->
 <tr>
 <td class="blanktotal" colspan="6" rowspan="6"></td>
 </tr>
 </tbody>
 </table>
 </body>
 </html>
<?php endif; ?>


protected/views/agenda/_viewmedico.php
<?php
/* @var $this AgendaController */
/* @var $data Agenda */
?>

<div class="view">

        <tr id="tabla_1">
        
	<?php echo '<td>'.$data->pktipoagenda->tipoagenda.'</td>' ?>

	<?php echo '<td>'.$data->pksubcentro->subcentro.'</td>' ?>

	<?php echo '<td>'.$data->nombreCompleto.'</td>' ?>

	<?php echo '<td>'.$data->numeroturno.'</td>' ?>               
        <?php 
        $var;
        $sql;
        $nombre = $data->nombre;
        if($data->atendido == 1){
            $var = true;
        } else{
           $var = false;
        }
        
        
        //dentro del checkbox se genera el evento onclick
        echo '<td>'.CHtml::Checkbox('atendidos', $var, array('value'=>false, 
            'onclick'=>"if(this.checked == true)"
            . "verdadero();"
            . "} else"
            . "{"
            . "falso();"
            . "}")).'</td>' 
        ?>       
        </tr>
        
        
    
	

</div>

protected/views/agenda/config.inc.php
<?php
error_reporting(E_ERROR | E_WARNING | E_PARSE);
date_default_timezone_set('Europe/Madrid');
$dbhost="localhost";
$dbname="calendario";
$dbuser="root";
$dbpass="joseluism";
$tabla="tcalendario";
$db = new mysqli($dbhost,$dbuser,$dbpass,$dbname);
if ($db->connect_errno) {
	die ("<h1>Fallo al conectar a MySQL: (" . $db->connect_errno . ") " . $db->connect_error."</h1>");
}
?>

protected/views/agenda/update.php
<?php
/* @var $this AgendaController */
/* @var $model Agenda */

$this->breadcrumbs=array(
	'Citas'=>array('admin'),
	//$model->idagenda=>array('view','id'=>$model->idagenda),
	'Actualizar',
);

$this->menu=array(
	array('label'=>'Lista de Citas', 'url'=>array('admin')),
	array('label'=>'Nueva Cita', 'url'=>array('create')),
	array('label'=>'Detalles de Cita', 'url'=>array('view', 'id'=>$model->idagenda)),
	//array('label'=>'Administrar citas', 'url'=>array('admin')),
);
?>

<h2>Actualizar Cita</h2>

<?php $this->renderPartial('_form_update', array('model'=>$model)); ?>